[tool.poetry]
name = "horology"
version = "1.2.0"
description = "Conveniently measures the time of loops, contexts and functions."
authors = ["mjmikulski <maciej.mikulski.jr@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
unittest = "^0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
