[project]
name = "horology"
version = "1.4.3"
description = "Conveniently measures the time of loops, contexts and functions."
authors = [{ name = "mjmikulski", email = "maciej.mikulski.jr@gmail.com" }]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.10"
keywords = ['timing', 'profiling', 'measure time', 'duration']
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Programming Language :: Python :: 3.15',
    'Typing :: Typed',
    'Topic :: Utilities',
    'Topic :: Software Development :: Libraries',
    'Topic :: Software Development :: Testing',
    'Topic :: Software Development :: Libraries :: Python Modules',
    "Operating System :: OS Independent"]

[project.urls]
Repository = 'https://github.com/mjmikulski/horology'

[dependency-groups]
dev = [
    "pytest==9.1.*",
    "mypy==2.4.*",
    "pytest-rerunfailures==16.*",
]

[tool.pytest.ini_options]
addopts = "--doctest-modules"

[build-system]
requires = ["poetry-core>=2.5"]
build-backend = "poetry.core.masonry.api"
