version: 2
jobs:

  build_3_8:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: python --version
      - checkout
      - run: pip install poetry
      - run: poetry install
      - run: pytest

  build_3_9:
    docker:
      - image: circleci/python:3.9
    steps:
      - run: python --version
      - checkout
      - run: pip install poetry
      - run: poetry install
      - run: pytest

  build_3_10:
    docker:
      - image: circleci/python:3.10
    steps:
      - run: python --version
      - checkout
      - run: pip install poetry
      - run: poetry install
      - run: pytest

  build_3_11:
    docker:
      - image: circleci/python:3.11
    steps:
      - run: python --version
      - checkout
      - run: pip install poetry
      - run: poetry install
      - run: pytest


workflows:
  version: 2
  build_and_test:
    jobs:
      - build_3_8
      - build_3_9
      - build_3_10
      - build_3_11
