version: 2
jobs:
  build_36:
    docker:
      - image: circleci/python:3.6
    steps:
      - run: python --version
      - checkout
      - run: pip install --user nose
      - run: nosetests -vv --with-doctest --doctest-options=+ELLIPSIS

  build_37:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: python --version
      - checkout
      - run: pip install --user nose
      - run: nosetests -vv --with-doctest --doctest-options=+ELLIPSIS

  build_38:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: python --version
      - checkout
      - run: pip install --user nose
      - run: nosetests -vv --with-doctest --doctest-options=+ELLIPSIS

  build_39:
    docker:
      - image: circleci/python:3.9
    steps:
      - run: python --version
      - checkout
      - run: pip install --user nose
      - run: nosetests -vv --with-doctest --doctest-options=+ELLIPSIS


workflows:
  version: 2
  build_and_test:
    jobs:
      - build_36
      - build_37
      - build_38
